version: '3'
services:

  script-ruby-app:
    container_name: RubyApp
    image: ruby@sha256:704b3369eb921a8b42239fbfb6c3ea443a72ed5e483be0eb8b97324cca6e4e2b #ruby:alpine
    tty: true
    network_mode: host
    command: sh -c "gem install net-ldap && sh"
    volumes:
      - ./ruby-app:/home/project


  script-ansible-app:
    container_name: AnsibleApp
    image: ansible/container-conductor-alpine-3.5@sha256:a16009d8cf4f3f55741abeddb0c92271ae5af89be5413a74b0699c42d5ea493f #ansible/container-conductor-alpine-3.5:0.9.3rc4
    tty: true
    network_mode: host
    command: /bin/sh -c "pip install boto3 && pip install boto && echo nameserver 8.8.8.8 > /etc/resolv.conf && /bin/sh "
    volumes:
      - ./ansible-app:/home/project